<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30651" started-at="2017-12-09T12:36:24Z" finished-at="2017-12-09T12:36:54Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="30651" started-at="2017-12-09T12:36:24Z" finished-at="2017-12-09T12:36:54Z">
      <class name="tests.TestDemo">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.TestDemo@1f97b55]" name="setUp" is-config="true" duration-ms="29404" started-at="2017-12-09T18:06:24Z" finished-at="2017-12-09T18:06:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="basePageNavigation()[pri:0, instance:tests.TestDemo@1f97b55]" name="basePageNavigation" duration-ms="74" started-at="2017-12-09T18:06:53Z" finished-at="2017-12-09T18:06:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Intentional Fail Scenario] but found [Go ahead and give it full test to checkout the amazing features behind our application]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Intentional Fail Scenario] but found [Go ahead and give it full test to checkout the amazing features behind our application]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at tests.TestDemo.basePageNavigation(TestDemo.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basePageNavigation -->
        <test-method status="PASS" signature="demoPassTest()[pri:0, instance:tests.TestDemo@1f97b55]" name="demoPassTest" duration-ms="62" started-at="2017-12-09T18:06:54Z" finished-at="2017-12-09T18:06:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoPassTest -->
        <test-method status="PASS" signature="afterSuitDriver()[pri:0, instance:tests.TestDemo@1f97b55]" name="afterSuitDriver" is-config="true" duration-ms="183" started-at="2017-12-09T18:06:54Z" finished-at="2017-12-09T18:06:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuitDriver -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.TestDemo@1f97b55]" name="teardown" is-config="true" duration-ms="0" started-at="2017-12-09T18:06:54Z" finished-at="2017-12-09T18:06:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.TestDemo -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
